apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: headlamp
  annotations:
    github.com/project-slug: backstage-itpl/headlamp/
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: kubernetes-component
    backstage.io/source-location: url:https://github.com/backstage-itpl/headlamp/src/main/
spec:
  type: service
  lifecycle: production
  owner: guests
